// resources/js/Components/FilterBar.vue
<script setup>
import { router } from '@inertiajs/vue3';
import { reactive, watch } from 'vue';

const props = defineProps({
    filters: { type: Object, required: true },
    options: { type: Object, required: true },
});

const state = reactive({
    q: props.filters.q ?? '',
    type: props.filters.type ?? '',
    protein: props.filters.protein ?? '',
    cost: props.filters.cost ?? '',
    tag: props.filters.tag ?? '',
});

let searchTimer = null;

function apply() {
    const params = Object.fromEntries(Object.entries(state).filter(([, v]) => v !== ''));
    router.get(route('recipes.index'), params, { preserveState: true, replace: true });
}

watch(() => [state.type, state.protein, state.cost, state.tag], apply);

watch(
    () => state.q,
    () => {
        clearTimeout(searchTimer);
        searchTimer = setTimeout(apply, 300);
    },
);

function clearAll() {
    Object.keys(state).forEach((k) => (state[k] = ''));
}

const hasFilters = () => Object.values(state).some((v) => v !== '');
</script>

<template>
    <div class="flex flex-wrap items-center gap-2">
        <input
            v-model="state.q"
            type="search"
            placeholder="Search recipes or ingredients…"
            class="w-64 rounded-lg border border-stone-300 bg-white px-3 py-1.5 text-sm focus:border-green-500 focus:outline-none focus:ring-1 focus:ring-green-500 dark:border-stone-700 dark:bg-stone-900"
        />
        <select v-model="state.type" class="rounded-lg border border-stone-300 bg-white px-2 py-1.5 text-sm capitalize dark:border-stone-700 dark:bg-stone-900">
            <option value="">All types</option>
            <option v-for="type in options.types" :key="type" :value="type">{{ type }}</option>
        </select>
        <select v-model="state.protein" class="rounded-lg border border-stone-300 bg-white px-2 py-1.5 text-sm capitalize dark:border-stone-700 dark:bg-stone-900">
            <option value="">All proteins</option>
            <option v-for="protein in options.proteins" :key="protein" :value="protein">{{ protein }}</option>
        </select>
        <select v-model="state.cost" class="rounded-lg border border-stone-300 bg-white px-2 py-1.5 text-sm dark:border-stone-700 dark:bg-stone-900">
            <option value="">Any cost</option>
            <option v-for="cost in options.costs" :key="cost" :value="cost">{{ cost }}</option>
        </select>
        <select v-model="state.tag" class="rounded-lg border border-stone-300 bg-white px-2 py-1.5 text-sm dark:border-stone-700 dark:bg-stone-900">
            <option value="">All tags</option>
            <option v-for="tag in options.tags" :key="tag" :value="tag">{{ tag }}</option>
        </select>
        <button v-if="hasFilters()" type="button" class="text-sm text-stone-500 hover:text-stone-800 dark:text-stone-400 dark:hover:text-stone-200" @click="clearAll">
            Clear
        </button>
    </div>
</template>

// remix/app/components/filter-bar.tsx
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router";

export interface FilterOptions {
  types: string[];
  proteins: string[];
  costs: string[];
  tags: string[];
}

const FILTER_KEYS = ["q", "type", "protein", "cost", "tag"] as const;
type FilterKey = (typeof FILTER_KEYS)[number];

export function FilterBar({ options }: { options: FilterOptions }) {
  const [searchParams, setSearchParams] = useSearchParams();

  const current = Object.fromEntries(
    FILTER_KEYS.map((k) => [k, searchParams.get(k) ?? ""]),
  ) as Record<FilterKey, string>;

  // Search input is locally controlled so typing isn't janky; it syncs to
  // the URL after a 300ms debounce.
  const [q, setQ] = useState(current.q);
  const timer = useRef<ReturnType<typeof setTimeout>>(null);

  function updateParams(changes: Partial<Record<FilterKey, string>>) {
    const next = { ...current, ...changes };
    const params = Object.fromEntries(
      Object.entries(next).filter(([, v]) => v !== ""),
    );
    setSearchParams(params, { replace: true, preventScrollReset: true });
  }

  function onSearchInput(value: string) {
    setQ(value);
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => updateParams({ q: value }), 300);
  }

  useEffect(() => () => {
    if (timer.current) clearTimeout(timer.current);
  }, []);

  const hasFilters = q !== "" || FILTER_KEYS.some((k) => current[k] !== "");

  function clearAll() {
    if (timer.current) clearTimeout(timer.current);
    setQ("");
    setSearchParams({}, { replace: true, preventScrollReset: true });
  }

  const selectClass =
    "rounded-lg border border-stone-300 bg-white px-2 py-1.5 text-sm dark:border-stone-700 dark:bg-stone-900";

  return (
    <div className="flex flex-wrap items-center gap-2">
      <input
        type="search"
        value={q}
        onChange={(e) => onSearchInput(e.target.value)}
        placeholder="Search recipes or ingredients…"
        className="w-64 rounded-lg border border-stone-300 bg-white px-3 py-1.5 text-sm focus:border-green-500 focus:outline-none focus:ring-1 focus:ring-green-500 dark:border-stone-700 dark:bg-stone-900"
      />
      <select
        value={current.type}
        onChange={(e) => updateParams({ type: e.target.value })}
        className={`${selectClass} capitalize`}
      >
        <option value="">All types</option>
        {options.types.map((type) => (
          <option key={type} value={type}>{type}</option>
        ))}
      </select>
      <select
        value={current.protein}
        onChange={(e) => updateParams({ protein: e.target.value })}
        className={`${selectClass} capitalize`}
      >
        <option value="">All proteins</option>
        {options.proteins.map((protein) => (
          <option key={protein} value={protein}>{protein}</option>
        ))}
      </select>
      <select
        value={current.cost}
        onChange={(e) => updateParams({ cost: e.target.value })}
        className={selectClass}
      >
        <option value="">Any cost</option>
        {options.costs.map((cost) => (
          <option key={cost} value={cost}>{cost}</option>
        ))}
      </select>
      <select
        value={current.tag}
        onChange={(e) => updateParams({ tag: e.target.value })}
        className={selectClass}
      >
        <option value="">All tags</option>
        {options.tags.map((tag) => (
          <option key={tag} value={tag}>{tag}</option>
        ))}
      </select>
      {hasFilters && (
        <button
          type="button"
          className="text-sm text-stone-500 hover:text-stone-800 dark:text-stone-400 dark:hover:text-stone-200"
          onClick={clearAll}
        >
          Clear
        </button>
      )}
    </div>
  );
}
